# add_puntuacion_and_tour_completado
# Revision ID: 14661a0073c9
# Revises: fa061d9b0299
# Create Date: 2026-06-28 02:46:48.352009+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14661a0073c9'
down_revision: Union[str, None] = 'fa061d9b0299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('puntuacion', sa.Integer(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('comentario_puntuacion', sa.Text(), nullable=True))
    op.add_column('usuarios', sa.Column('tour_completado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'tour_completado')
    op.drop_column('ajustes_razonables', 'comentario_puntuacion')
    op.drop_column('ajustes_razonables', 'puntuacion')
    # ### end Alembic commands ###
