# add_creado_por_to_ajustes_razonables
# Revision ID: fa061d9b0299
# Revises: c389e717b426
# Create Date: 2026-06-27 22:32:19.717515+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa061d9b0299'
down_revision: Union[str, None] = 'c389e717b426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('creado_por', sa.UUID(), nullable=True))
    op.create_index('ajustes_razonables_creado_por_idx', 'ajustes_razonables', ['creado_por'], unique=False)
    op.create_foreign_key(None, 'ajustes_razonables', 'usuarios', ['creado_por'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ajustes_razonables', type_='foreignkey')
    op.drop_index('ajustes_razonables_creado_por_idx', table_name='ajustes_razonables')
    op.drop_column('ajustes_razonables', 'creado_por')
    # ### end Alembic commands ###
