# add_atenciones_medicas_medicamentos_lista_jsonb
# Revision ID: fdaf717bf93e
# Revises: ae8212f3873c
# Create Date: 2026-07-18 01:39:27.827640+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdaf717bf93e'
down_revision: Union[str, None] = 'ae8212f3873c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entornos_salud', sa.Column('atenciones_medicas', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('entornos_salud', sa.Column('medicamentos_lista', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entornos_salud', 'medicamentos_lista')
    op.drop_column('entornos_salud', 'atenciones_medicas')
    # ### end Alembic commands ###
