# add_dba_referencia_to_ajustes
# Revision ID: ae8212f3873c
# Revises: a8e941ed1425
# Create Date: 2026-07-16 00:22:28.468099+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8212f3873c'
down_revision: Union[str, None] = 'a8e941ed1425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('dba_referencia', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ajustes_razonables', 'dba_referencia')
    # ### end Alembic commands ###
