# add_titulo_tema_to_ajustes
# Revision ID: 635e02914f53
# Revises: 728f75c13a3c
# Create Date: 2026-06-23 23:53:07.473949+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635e02914f53'
down_revision: Union[str, None] = '728f75c13a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('titulo_tema', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ajustes_razonables', 'titulo_tema')
    # ### end Alembic commands ###
