# Add periodos_academicos
# Revision ID: 5d5aa9fc21f6
# Revises: 5d69752d74b9
# Create Date: 2026-06-23 00:56:54.819169+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5aa9fc21f6'
down_revision: Union[str, None] = '5d69752d74b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
