# replace_piar_fields_with_tipo_ajuste_apoyo_requerido
# Revision ID: 6837d5a7f971
# Revises: 7471145b4d4d
# Create Date: 2026-07-15 20:08:20.689923+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6837d5a7f971'
down_revision: Union[str, None] = '7471145b4d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('tipo_ajuste', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('apoyo_requerido', sa.Text(), nullable=True))
    op.drop_column('ajustes_razonables', 'temporalidad')
    op.drop_column('ajustes_razonables', 'recursos_talento_humano')
    op.drop_column('ajustes_razonables', 'meta_flexibilizada')
    op.drop_column('ajustes_razonables', 'responsable')
    op.drop_column('ajustes_razonables', 'recursos_tecnicos')
    op.drop_column('ajustes_razonables', 'recursos_comunicativos')
    op.drop_column('ajustes_razonables', 'medios_verificacion')
    op.drop_column('ajustes_razonables', 'recursos_tecnologicos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('recursos_tecnologicos', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ajustes_razonables', sa.Column('medios_verificacion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ajustes_razonables', sa.Column('recursos_comunicativos', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ajustes_razonables', sa.Column('recursos_tecnicos', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ajustes_razonables', sa.Column('responsable', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ajustes_razonables', sa.Column('meta_flexibilizada', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ajustes_razonables', sa.Column('recursos_talento_humano', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ajustes_razonables', sa.Column('temporalidad', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('ajustes_razonables', 'apoyo_requerido')
    op.drop_column('ajustes_razonables', 'tipo_ajuste')
    # ### end Alembic commands ###
