# Link ajustes a periodos
# Revision ID: 14cb46b310db
# Revises: 5d5aa9fc21f6
# Create Date: 2026-06-23 01:21:39.077499+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cb46b310db'
down_revision: Union[str, None] = '5d5aa9fc21f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('periodo_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'ajustes_razonables', 'periodos_academicos', ['periodo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ajustes_razonables', 'trimestre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('trimestre', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ajustes_razonables', type_='foreignkey')
    op.drop_column('ajustes_razonables', 'periodo_id')
    # ### end Alembic commands ###
