# add_piar_oficial_fields
# Revision ID: 7471145b4d4d
# Revises: 35d5be05480d
# Create Date: 2026-07-15 19:11:25.389471+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7471145b4d4d'
down_revision: Union[str, None] = '35d5be05480d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('meta_flexibilizada', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('recursos_talento_humano', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('recursos_tecnicos', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('recursos_tecnologicos', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('recursos_comunicativos', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('temporalidad', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('responsable', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('medios_verificacion', sa.Text(), nullable=True))
    op.add_column('caracteristicas_estudiante', sa.Column('caracterizacion_pedagogica', sa.Text(), nullable=True))
    op.add_column('caracteristicas_estudiante', sa.Column('expectativas_estudiante', sa.Text(), nullable=True))
    op.add_column('caracteristicas_estudiante', sa.Column('expectativas_familia', sa.Text(), nullable=True))
    op.add_column('caracteristicas_estudiante', sa.Column('redes_apoyo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caracteristicas_estudiante', 'redes_apoyo')
    op.drop_column('caracteristicas_estudiante', 'expectativas_familia')
    op.drop_column('caracteristicas_estudiante', 'expectativas_estudiante')
    op.drop_column('caracteristicas_estudiante', 'caracterizacion_pedagogica')
    op.drop_column('ajustes_razonables', 'medios_verificacion')
    op.drop_column('ajustes_razonables', 'responsable')
    op.drop_column('ajustes_razonables', 'temporalidad')
    op.drop_column('ajustes_razonables', 'recursos_comunicativos')
    op.drop_column('ajustes_razonables', 'recursos_tecnologicos')
    op.drop_column('ajustes_razonables', 'recursos_tecnicos')
    op.drop_column('ajustes_razonables', 'recursos_talento_humano')
    op.drop_column('ajustes_razonables', 'meta_flexibilizada')
    # ### end Alembic commands ###
