# add_temporalidad_responsable_medios_to_ajustes
# Revision ID: a8e941ed1425
# Revises: 6837d5a7f971
# Create Date: 2026-07-15 21:29:40.035837+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e941ed1425'
down_revision: Union[str, None] = '6837d5a7f971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajustes_razonables', sa.Column('temporalidad', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('responsable', sa.Text(), nullable=True))
    op.add_column('ajustes_razonables', sa.Column('medios_verificacion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ajustes_razonables', 'medios_verificacion')
    op.drop_column('ajustes_razonables', 'responsable')
    op.drop_column('ajustes_razonables', 'temporalidad')
    # ### end Alembic commands ###
