# add_medical_support_to_health_env
# Revision ID: c389e717b426
# Revises: 635e02914f53
# Create Date: 2026-06-24 15:25:28.919591+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c389e717b426'
down_revision: Union[str, None] = '635e02914f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entornos_salud', sa.Column('soporte_medico_nombre', sa.Text(), nullable=True))
    op.add_column('entornos_salud', sa.Column('soporte_medico_archivo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entornos_salud', 'soporte_medico_archivo')
    op.drop_column('entornos_salud', 'soporte_medico_nombre')
    # ### end Alembic commands ###
