# agregar evidencias_ajuste
# Revision ID: 64d5823839b1
# Revises: 60779a0da570
# Create Date: 2026-07-03 14:57:46.710882+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d5823839b1'
down_revision: Union[str, None] = '60779a0da570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
