# add parent contact fields and acudiente_principal to entornos_hogar
# Revision ID: 95b7f7656d79
# Revises: 14661a0073c9
# Create Date: 2026-06-28 16:49:59.216234+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b7f7656d79'
down_revision: Union[str, None] = '14661a0073c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entornos_hogar', sa.Column('telefono_madre', sa.Text(), nullable=True))
    op.add_column('entornos_hogar', sa.Column('correo_madre', sa.Text(), nullable=True))
    op.add_column('entornos_hogar', sa.Column('numero_documento_madre', sa.Text(), nullable=True))
    op.add_column('entornos_hogar', sa.Column('telefono_padre', sa.Text(), nullable=True))
    op.add_column('entornos_hogar', sa.Column('correo_padre', sa.Text(), nullable=True))
    op.add_column('entornos_hogar', sa.Column('numero_documento_padre', sa.Text(), nullable=True))
    op.add_column('entornos_hogar', sa.Column('acudiente_principal', sa.Text(), nullable=True))
    op.create_index(op.f('ix_entornos_hogar_numero_documento_madre'), 'entornos_hogar', ['numero_documento_madre'], unique=False)
    op.create_index(op.f('ix_entornos_hogar_numero_documento_padre'), 'entornos_hogar', ['numero_documento_padre'], unique=False)
    op.create_check_constraint(
        "ck_entornos_hogar_acudiente",
        "entornos_hogar",
        "acudiente_principal IN ('madre', 'padre', 'cuidador') OR acudiente_principal IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("ck_entornos_hogar_acudiente", "entornos_hogar", type_="check")
    op.drop_index(op.f('ix_entornos_hogar_numero_documento_padre'), table_name='entornos_hogar')
    op.drop_index(op.f('ix_entornos_hogar_numero_documento_madre'), table_name='entornos_hogar')
    op.drop_column('entornos_hogar', 'acudiente_principal')
    op.drop_column('entornos_hogar', 'numero_documento_padre')
    op.drop_column('entornos_hogar', 'correo_padre')
    op.drop_column('entornos_hogar', 'telefono_padre')
    op.drop_column('entornos_hogar', 'numero_documento_madre')
    op.drop_column('entornos_hogar', 'correo_madre')
    op.drop_column('entornos_hogar', 'telefono_madre')
    # ### end Alembic commands ###
