# agregar codigo_acceso_familia
# Revision ID: 3abdca792cd8
# Revises: fix_auditoria_constraint
# Create Date: 2026-07-03 16:43:24.073853+00:00

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abdca792cd8'
down_revision: Union[str, None] = 'fix_auditoria_constraint'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiantes', sa.Column('codigo_acceso_familia', sa.Text(), nullable=True))
    op.add_column('estudiantes', sa.Column('email_acudiente', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'estudiantes', ['codigo_acceso_familia'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estudiantes', type_='unique')
    op.drop_column('estudiantes', 'email_acudiente')
    op.drop_column('estudiantes', 'codigo_acceso_familia')
    # ### end Alembic commands ###
